// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gowtvvaijekpgozygrzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvd3R2dmFpamVrcGdvenlncnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMzM3ODIsImV4cCI6MjA3NjcwOTc4Mn0.hgA7ppBnfiXEBDT4VATPpmqCa08rtaBlaT44G3KGexs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});